import {
    BadgePercent,
    BookMarked,
    Boxes,
    Building2,
    CalendarClock,
    ChartColumn,
    ChartGantt,
    ClipboardCheck,
    ClipboardList,
    Factory,
    FileSpreadsheet,
    FlaskConical,
    Folder,
    Gauge,
    Grid3x3,
    HardHat,
    Heart,
    Layers3,
    LayoutDashboard,
    ListChecks,
    MapPinned,
    Megaphone,
    Package,
    PackageCheck,
    PackageSearch,
    Palette,
    Ruler,
    Settings,
    SquareKanban,
    Tags,
    ShieldCheck,
    Truck,
    UserPlus,
    Users,
    Warehouse,
    History,
} from "lucide-react"

/**
 * Panel navigasyonunun ikon sözlüğü. Nav tanımları ada göre seçer; böylece
 * tanımlar saf veri kalır ve sunucu bileşenlerinden istemciye geçebilir.
 *
 * Müşteri portalının ikonları da burada: kalan paneller taşındığında sözlük
 * yeniden bölünmesin.
 */
export const panelNavIcons = {
    dashboard: LayoutDashboard,
    folder: Folder,
    boxes: Boxes,
    package: Package,
    clipboard: ClipboardList,
    "clipboard-check": ClipboardCheck,
    flask: FlaskConical,
    palette: Palette,
    layers: Layers3,
    ruler: Ruler,
    settings: Settings,
    users: Users,
    truck: Truck,
    building: Building2,
    map: MapPinned,
    megaphone: Megaphone,
    shield: ShieldCheck,
    sheet: FileSpreadsheet,
    heart: Heart,
    bookmark: BookMarked,
    discount: BadgePercent,
    "package-search": PackageSearch,
    "package-check": PackageCheck,
    "calendar-clock": CalendarClock,
    "user-plus": UserPlus,
    factory: Factory,
    warehouse: Warehouse,
    "hard-hat": HardHat,
    grid: Grid3x3,
    gantt: ChartGantt,
    kanban: SquareKanban,
    tags: Tags,
    "list-checks": ListChecks,
    history: History,
    gauge: Gauge,
    chart: ChartColumn,
} as const
