/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Ceyhunlar-Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "CeyhunlarAdminApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CeyhunlarClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "CeyhunlarOwnerApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CeyhunlarProtectedApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CeyhunlarPublicApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CeyhunlarUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "CeyhunlarWebBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}